services:
  - type: web
    name: My Todo App
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run web-app-todo.py -- server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PORT
        value: 10000